Repository jenkinsci/mina-sshd-api-plugin, pull requests merged in 2022-07, with the labels that each got.

#15 [chore] Fix deps management of modules that are in bom
  mina-sshd-api-core/pom.xml
  mina-sshd-api-scp/pom.xml
  mina-sshd-api-sftp/pom.xml
  pom.xml
Labels: dependencies

#13 [JENKINS-64105] Add optional SSHAuthenticator implementation
  mina-sshd-api-core/pom.xml
  mina-sshd-api-core/src/main/java/io/jenkins/plugins/mina_sshd_api/core/authenticators/MinaSSHPasswordKeyAuthenticator.java
  mina-sshd-api-core/src/main/java/io/jenkins/plugins/mina_sshd_api/core/authenticators/MinaSSHPublicKeyAuthenticator.java
  mina-sshd-api-core/src/main/test/io/jenkins/plugins/mina_sshd_api/core/authenticators/MinaSSHPasswordKeyAuthenticatorTest.java
  mina-sshd-api-core/src/main/test/io/jenkins/plugins/mina_sshd_api/core/authenticators/MinaSSHPublicKeyAuthenticatorTest.java
  pom.xml
Labels: enhancement

#24 Move tests to correct directory
  mina-sshd-api-core/src/test/java/io/jenkins/plugins/mina_sshd_api/core/authenticators/MinaSSHPasswordKeyAuthenticatorTest.java
  mina-sshd-api-core/src/test/java/io/jenkins/plugins/mina_sshd_api/core/authenticators/MinaSSHPublicKeyAuthenticatorTest.java
Labels: developer

#20 bump bom and jenkins version
  mina-sshd-api-core/pom.xml
  pom.xml
Labels: bug, dependencies

#25 Bump bom-2.319.x from 1508.v4b_d09ff0e893 to 1539.v6a_85813638f8
  mina-sshd-api-core/pom.xml
  pom.xml
Labels: dependencies
